<?php

namespace SMRG\GeoserverBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrackPictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackPictureRepository extends EntityRepository
{
}
